/*
 * Derives scripts/ignite/bundle/themes/tokens.css from the bundled Ignite theme
 * (scripts/ignite/bundle/themes/cms.css). Run by `npm run build:ignite`.
 *
 * The Ignite components render in shadow DOM and only need the theme's --xe-*
 * custom properties, which inherit into their shadow roots from :root. cms.css
 * also ships global element styles (a * { margin: 0; padding: 0 } reset plus
 * body/h1–h6/p/a typography) that would restyle every EDS block on the page,
 * and switches to dark tokens under prefers-color-scheme, which the rest of the
 * site doesn't support. This keeps the token sections and drops:
 *
 *   - the `tokens/foundations/base.css` and `themes/cms.css` sections;
 *   - the `@media (prefers-color-scheme: dark)` block (the opt-in
 *     `:root[data-theme=dark]` tokens stay).
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const THEMES = fileURLToPath(new URL('../../scripts/ignite/bundle/themes/', import.meta.url));
const SOURCE = `${THEMES}cms.css`;
const TARGET = `${THEMES}tokens.css`;

const DROPPED_SECTIONS = ['tokens/foundations/base.css', 'themes/cms.css'];
const SECTION_MARKER = /^\/\* scripts\/ignite\/dist\/(\S+) \*\/$/;

/** Removes each `@media (prefers-color-scheme: dark) { … }` block, braces balanced. */
function dropAutoDarkMode(css) {
  const opener = '@media (prefers-color-scheme: dark) {';
  let out = css;
  let start = out.indexOf(opener);
  while (start !== -1) {
    let depth = 0;
    let end = start + opener.length - 1;
    for (; end < out.length; end += 1) {
      if (out[end] === '{') depth += 1;
      if (out[end] === '}') {
        depth -= 1;
        if (depth === 0) break;
      }
    }
    out = out.slice(0, start) + out.slice(end + 1);
    start = out.indexOf(opener);
  }
  return out;
}

const lines = readFileSync(SOURCE, 'utf8').split('\n');
const kept = [];
let dropping = false;
lines.forEach((line) => {
  const marker = line.match(SECTION_MARKER);
  if (marker) dropping = DROPPED_SECTIONS.includes(marker[1]);
  if (!dropping) kept.push(line);
});

const header = '/* Generated by tools/ignite/extract-tokens.mjs from cms.css — do not edit. */';
const [first, ...rest] = kept;
// @import must stay the first statement, so the header goes after it.
const body = first.startsWith('@import') ? [first, header, ...rest] : [header, first, ...rest];
const tokens = dropAutoDarkMode(body.join('\n')).replace(/\n{3,}/g, '\n\n');

writeFileSync(TARGET, tokens.endsWith('\n') ? tokens : `${tokens}\n`);
// eslint-disable-next-line no-console -- build script output
console.log(`Wrote ${TARGET}`);
